[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "countries-currencies-mcp"
version = "0.1.0"
dependencies = [
    "mcp",
    "httpx"
]

[project.scripts]
countries-currencies-mcp = "countries_currencies.server:main"
