[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "current-date-time-mcp"
version = "0.1.0"
dependencies = [
    "mcp"
]

[project.scripts]
current-date-time-mcp = "current_date_time.server:main"
