[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "wikipedia-mcp"
version = "0.1.0"
dependencies = [
    "mcp",
    "httpx"
]

[project.scripts]
wikipedia-mcp = "wikipedia_mcp.server:main"