[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlite-read-server-mcp"
version = "0.1.0"
dependencies = [
    "mcp",
]

[project.scripts]
sqlite-read-server-mcp = "sqlite_read_server.server:main"
