[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "weather-geocoding-mcp"
version = "0.1.0"
dependencies = [
    "mcp",
    "httpx"
]

[project.scripts]
weather-geocoding-mcp = "weather_geocoding.server:main"
